version: '3.7'

services:
  shipsrest-web:
    build: ${IMAGE_NGINX}
    container_name: ${NAME_SERVER_NGINX}
    ports:
      - ${PORT_LOCAL_SERVER_NGINX}:${PORT_CONTAINER_SERVER}
      - ${PORT_LOCAL_SERVER_NGINX_SSL}:${PORT_CONTAINER_SERVER_SSL}
    volumes:
      - ${PATH_DIRECTORY_SERVER}:${PATH_DIRECTORY_SERVER_DEST}
    restart: unless-stopped
    image: ${NAME_SERVER_NGINX}
    depends_on:
      - shipsrest-back
    networks:
      - shipsrest-network
  shipsrest-back:
    build: ${IMAGE_PHP_FPM}
    container_name: ${NAME_PHP_FPM}
    restart: unless-stopped
    volumes:
      - ${PATH_DIRECTORY_SERVER}:${PATH_DIRECTORY_SERVER_DEST}
    command: sh -c "composer install --ignore-platform-reqs"
    image: ${NAME_PHP_FPM}
    networks:
      - shipsrest-network
networks:
  shipsrest-network:
    driver: bridge