version: '3.7'

services:
  php-apache:
    build: ${IMAGE_PHP}
    container_name: ${NAME_SERVER}
    ports:
      - ${PORT_LOCAL_SERVER}:${PORT_CONTAINER_SERVER}
    volumes:
      - ${PATH_DIRECTORY_SERVER}:${PATH_DIRECTORY_SERVER_DEST}
    depends_on:
      - mysql
  mysql:
    image: ${IMAGE_DATABASE}
    container_name: ${NAME_DATABASE}
    restart: always
    ports:
      - ${PORT_LOCAL_DATABASE}:${PORT_CONTAINER_DATABASE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DATABASE}
      MYSQL_DATABASE: ${MYSQL_NAME_DATABASE}
      MYSQL_USER: ${MYSQL_USER_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DATABASE}
      MYSQL_VERSION: ${MYSQL_VERSION_DATABASE}
    expose:
      - ${PORT_CONTAINER_DATABASE}
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: